name: headerchecker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: get headerchecker and validate
      uses: nicpalmer/headerchecker@v0.1
      
    - name: Build
      run: go build -o headerchecker main.go

    - name: Check that headerchecker can run
      run: chmod +x headerchecker
   
    - name: Test a simple URL
      run: ./headerchecker --url 'https://bbc.co.uk'
